POST http://localhost:3003/api/users
Content-Type: application/json

{
    "blogs": [],
    "username": "mike",
    "name": "Mike Arsenault",
    "password": "adfafeawe"
}

###
Delete http://localhost:3003/api/users/611184bc2d472ca5516da1db