GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/5a422a851b54a676234d17f7

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "YOU’RE DOING IT WRONG: 7 TIPS TO RECYCLE BETTER",
    "author": "doney",
    "url": "https://www.earthday.org/youre-doing-it-wrong-7-tips-to-recycle-better/",
    "likes": 65,
    "userId": "6111898a24277a216c84ad01"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Why Be a Vegetarian? Consider Your Health",
  "author": "VEGETARIAN TIMES EDITORS",
  "url": "https://www.vegetariantimes.com/health-nutrition/plant-based-diet/why-go-veg-learn-about-becoming-a-vegetarian/",
  "likes": 34
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "beer",
  "author": "mok",
  "url": "www.beer.com",
  "likes": 24
}

###
DELETE http://localhost:3003/api/blogs/61046c8a52541d9b2a35aad7

###
PUT http://localhost:3003/api/blogs/6101b91eb884336c95dc960f
Content-Type: application/json

{   
  "title": "beer",
  "author": "mok",
  "url": "updatedUrl.com",
  "likes": 54
}