GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Climate Change",
  "author": "mok",
  "url": "www.climate-change.com",
  "likes": 30495
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "beer",
  "author": "mok",
  "url": "www.beer.com",
  "likes": 24
}