POST http://localhost:3003/api/users
Content-Type: application/json

{
    "blogs": [],
    "username": "doney",
    "name": "John Doe",
    "password": "skjeowek"
}

###
Delete http://localhost:3003/api/users/611184bc2d472ca5516da1db