GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/60d51bfee386e58f145acd08

###
DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Hyeeun Mok",
  "number": "555-555-5555"
}